ARG OS_VER=latest
FROM debian:${OS_VER}
COPY .devcontainer/features/musl-cross/install.sh /root/musl-cross.sh
RUN set -eux;\
    apt-get update;\
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends\
 build-essential\
 ca-certificates\
 file\
 qemu-user\
 wget\
;\
    env ARCHITECTURES='aarch64 riscv64 x86_64' /root/musl-cross.sh;\
    apt-get clean; rm -rf /var/lib/apt/lists/* /root/musl-cross.sh;\
    echo DONE
