FROM centos:centos7
RUN set -eux;\
    yum -y install\
 file\
 gcc\
 make\
 tar\
 wget\
    ;\
    yum -y install \
 https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm\
 https://repo.ius.io/ius-release-el7.rpm\
    ;\
    yum -y install\
 git236-core\
 qemu-user\
    ;\
    yum clean all;\
    echo DONE
COPY .devcontainer/features/musl-cross/install.sh /root/musl-cross.sh
RUN set -eux;\
    env ARCHITECTURES='aarch64 riscv64 x86_64' /root/musl-cross.sh;\
    rm -f /root/musl-cross.sh;\
    echo DONE
