FROM centos:centos7
RUN set -eux;\
    yum -y install\
 curl\
 file\
 gcc\
 make\
 tar\
    ;\
    yum -y install \
 https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm\
    ;\
    yum -y install\
 qemu-user\
    ;\
    yum clean all;\
    echo DONE
RUN set -eux;\
    cd /tmp;\
    for f in git-2.35.7.tar.xz; do\
        curl -o $f --location --show-error https://github.com/TheCBaH/git.builder/releases/download/v0.0.1/$f;\
        xz -d $f ; f=${f%.xz};\
        tar -xf $f -C /usr/local;\
        rm -f $f;\
    done;\
    echo DONE
COPY .devcontainer/features/musl-cross/install.sh /root/musl-cross.sh
RUN set -eux;\
    env ARCHITECTURES='aarch64 riscv64 x86_64' /root/musl-cross.sh;\
    rm -f /root/musl-cross.sh;\
    echo DONE
