FROM centos:centos6
RUN set -eux;\
    version="$(awk '/release/{print $3}' /etc/issue)";\
    mirror='linuxsoft.cern.ch/centos-vault';\
    sed -i -r\
     -e "s,^#(baseurl=http://)[a-z]+(\.centos\.org/)centos/(.+)/(.+)/(.+)/,\1$mirror/$version/\4/\5,"\
     -e 's/^(mirrorlist=)/#\1/'\
      /etc/yum.repos.d/*.repo;\
    yum -v --noplugins repolist;\
    yum -v -y --noplugins install\
 curl\
 gcc\
 make\
 xz\
    ;\
    yum clean all;\
    echo DONE
RUN set -eux;\
    cd /tmp;\
    for f in git-2.35.7.tar.xz; do\
        curl -o $f --location --show-error https://github.com/TheCBaH/git.builder/releases/download/v0.0.1/$f;\
        xz -d $f ; f=${f%.xz};\
        tar -xf $f -C /usr/local;\
        rm -f $f;\
    done;\
    echo DONE
COPY .devcontainer/features/musl-cross/install.sh /root/musl-cross.sh
RUN set -eux;\
    env ARCHITECTURES='aarch64 riscv64 x86_64' /root/musl-cross.sh;\
    rm -f /root/musl-cross.sh;\
    echo DONE
