name: images

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: debian
      uses: ./.github/workflows/actions/docker
      with:
        image: debian
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: ubuntu
      uses: ./.github/workflows/actions/docker
      with:
        image: ubuntu
        password: ${{ secrets.GITHUB_TOKEN }}
  devcontainer:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: image
      uses: ./.github/workflows/actions/devcontainer
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
